version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Run ci checks
          command: npm run ci-check

workflows:
  version: 2
  main:
    jobs:
      - test
